---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
      solveButton: false
    - name: module-01
      label: "DEFEND: Vulnerability Response"
      solveButton: false
    - name: module-02
      label: "CONTAIN: Policy-Gated Patching"
      solveButton: false
    - name: module-03
      label: "COMPLY: Container Supply Chain"
      solveButton: false
    - name: conclusion
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "Terminal"
    url: /wetty_central
  - name: AAP Controller
    url: https://control-${guid}.${domain}/
    external: false
  - name: EDA Controller
    url: https://eda-${guid}.${domain}/
    external: false
  - name: Splunk
    url: https://splunk-http-${guid}.${domain}
    external: true
  - name: OPA
    url: https://opa-http-${guid}.${domain}
    external: false
  - name: HashiCorp Vault
    url: https://vault-${guid}.${domain}/ui/vault/unseal
    external: true
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
    external: false
